### ISSUE TITLE
Move all literal values to Constants.java

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Sportbot_Code#49]
All literal values in the code such as `1, 0.4, etc.` should be move the Constants.java with their own subclasses for each subsystem (similar to how RobotMap.java has `public static class mapDriveTrain`).

The benefit of this is so that all the constants are in one easy to find place and if some constants are used more than once, we just update the code once

# Example:
## Constants.java
```java
public static class constDriveTrain {
  public static final int SLOW_MODE_MULTIPLIER = 0.5;
}
```
## setDrivetrainSpeed method in Drivetrain.java
```java
if (slowModeActivated) {
      forwardVelocity = forwardVelocity * Constants.constDriveTrain.SLOW_MODE_MULTIPLIER;
      rotationSpeed = rotationSpeed * Constants.constDriveTrain.SLOW_MODE_MULTIPLIER;
    }
```

**Comment by S0L0GUY** [comment]
I'm scared, why was this thread re-opened?

**Comment by TaylerUva** [comment]
There are other commands that still have literals

**Comment by S0L0GUY** [comment]
Do I also add constants for the literals that just hold a value of 0?
